### PR TITLE
Proposition to solve issue #190

### PR DESCRIPTION
**Pull request by clementval**
Allows `DATA` statement when inexec state. 
#190

### CODE REVIEW

**Comment by h-murai** [comment]
@shingo-s I think that Hirano-san and I have discussed this issue before. Please review this PR.

**Comment by xmp-mh** [comment]
This is Hirano.
Fixes themselves are OK but Shingo-san and I just found there are no backend-side modifications that are needed to accept the new "FDataStatement" in XcodeML. Forgot to commit?

**Comment by clementval** [comment]
@xmp-mh Sorry, just forgot to push it. Just for the file XcodeML-Exc-Tools/src/exc/object/Xcode.java, it is written that it is normally generated but I cannot find the `./genXcodeJava.pl` file. 

```java
/*
 * This class is generated by ./genXcodeJava.pl
 */
```

**Comment by shingo-s** [comment]
LGTM👍

**Comment by xmp-mh** [comment]
@clementval
Sorry for my sluggish response.

No the perl script "genXcodeJava.pl" doesn't exists for now with unclear reason and I know it does exist. I checked an old SVN workspace (managed by git-svn) and found it: 54ab3eca95d0c6a31e01ede05b01ec5b14bc5d4c (Could someone check that this hash is included in the current repository or not?)
Anyway, it is better to generate this kinda enum-ish data automatically so we should revive the perl script. Even so the backend-side fixes are OK.

**Comment by clementval** [comment]
@xmp-mh Totally agree that it's better to generate it with the script.

**Comment by xmp-mh** [comment]
@clementval I pointed this issue out to Murai-san and the whether the script revives or not would be discussed/decided.

**Comment by clementval** [comment]
@xmp-mh Ok thanks!

**Comment by xmp-mh** [comment]
@clementval
The script and def. file were accidentally removed at svn -> git migration phase. Now I requested to revive those. And furthermore the script is too OLD enough to have perl version incompatibilities so we have to modify it suitable for the current perl syntax. I am working on the modification at this moment.

**Comment by xmp-mh** [comment]
@clementval
Please renew this PR with followings (I believe you know well about this though :) :
1) Save your current Xcode.java since the latest master branch doesn't have it.
2) Merge the latest master into the topic branch.
3) Manually merge your Xcode.java, which is saved in 1), into Xcode.def.

**Comment by clementval** [comment]
@xmp-mh I made the requested changes for `Xcode.def`

**Comment by xmp-mh** [comment]
@clementval The PR LGTM.

**Pull request merged**
