### PR TITLE
DO CONCURRENT

### PR DESCRIPTION
**Pull request by shingo-s**
This pull request will implement DO CONCURRENT syntax.

ex)
```
 do concurrent (i=1:m)
    a(k+i) = a(k+i) + factor*a(l+i)
 end do
```

### CODE REVIEW

**Comment by h-murai** [comment]
@shingo-s pls resolve the conflict.

**Comment by shingo-s** [comment]
@h-murai I fixed it.

**Comment by h-murai** [comment]
@shingo-s The example code above is translated as follows. The variables m, k, factor, and l should be declared outside the BLOCK construct.

```fortran
 BLOCK
# 5 "hoge.f90"
  INTEGER :: omnitmp000
  INTEGER :: m
  INTEGER :: k
  REAL :: factor
  INTEGER :: l

# 5 "hoge.f90"
  DO CONCURRENT ( omnitmp000 = 1 : m )
# 6 "hoge.f90"
   a ( k + omnitmp000 ) = a ( k + omnitmp000 ) + factor * a ( l + omnitmp000 )
  END DO
 END BLOCK
```

**Comment by shingo-s** [comment]
@h-murai I fixed bugs.

**Pull request merged**
