### PR TITLE
Fix #379

### LINKED ISSUE #379: Mis reference of a procedure
A procedure refers the wrong interface which is in the parent scope.

```fortran
      SUBROUTINE s()
        INTERFACE
          FUNCTION x()    !! p should refer this x
          END FUNCTION
        END INTERFACE
        PROCEDURE(x), POINTER :: p
      END

      INTERFACE
        FUNCTION x()    !! BUT p refer this
        END FUNCTION
      END INTERFACE
      END
```

### PR DESCRIPTION
**Pull request by shingo-s**
This pull request will fix #379.

However, the sample code doesn't work yet due to ##363.

### CODE REVIEW

**Comment by h-murai** [comment]
@shingo-s It looks to me that the procedure pointer could refer to the right function without this PR. What's the problem of #379 and how should it be resolved?

```xml
    <FfunctionType type="F18d8950" return_type="Fcomplex">
      <params>
      </params>
    </FfunctionType>
    ...
    <FbasicType type="F18db2b0" is_pointer="true" is_procedure="true" ref="F18d8950"/>
```

**Comment by shingo-s** [comment]
@h-murai Sorry. This test data is not good for this issue. So I added better test data.

**Comment by shingo-s** [comment]
@h-murai I solved merge conflict! Please merge this.

**Comment by h-murai** [comment]
@shingo-s Again, what's the problem of #379? It looks to me that no differences are found in the output xml files even if this PR is applied.

**Comment by shingo-s** [comment]
691bc8c2 has already fix #379, this pull reuqest has no effect on the #379

**Pull request closed without merging**
