### PR TITLE
Implements ERROR STOP statement

### PR DESCRIPTION
**Pull request by shingo-s**
This pull request will implement ERROR STOP statement and translate it to `FerrorStopStatement` in XcodeML.

### CODE REVIEW

**Comment by h-murai** [comment]
This code causes an error.

```fortran
program test
  error stop (5+4)
end program test
```

**Comment by shingo-s** [comment]
@h-murai sorry, I missed the specification.

I'll fix it soon, how its XcodeML should be?
If there is no problem, I'll use the child element `code` for the integer constant expression and `message` for the character constant expression.

```fortran
program test
  INTEGER, PARAMETER, DIMENSION(3) :: p = (/1,2,3/)
  error stop p(1)
end program test
```

```xml
  <FerrorStopStatement lineno="4" file="test.f90">
    <code>
      <FarrayRef type="I7cd270">
         ...
      </FarrayRef>
    </code>
  </FerrorStopStatement>
```

**Comment by h-murai** [comment]
@shingo-s I agree your proposal about XcodeML.

**Comment by h-murai** [comment]
@shingo-s Sorry. I jumped to the wrong conclusion.

The following code should be accepted because the code of STOP/ERROR STOP may be char-constant-expr.

```fortran
program test
  error stop 'foo' // 'bar'
end program test
```

**Comment by shingo-s** [comment]
I fixed for char-constant-expr ('//' was not regarded as a part of the constant expression).

Now above code will be translated into:

```xml
        <FerrorStopStatement lineno="5" file="../test/testdata/error_stop_with_constant_expressions.f90">
          <message>
            <FconcatExpr type="C83e420">
              <FcharacterConstant type="C83e0e0">foo</FcharacterConstant>
              <FcharacterConstant type="C83e280">bar</FcharacterConstant>
            </FconcatExpr>
          </message>
        </FerrorStopStatement>
```

**Comment by h-murai** [comment]
@shingo-s Not only '//' but also any char-constant-expr must be accepted. For example, the following code should also be accepted.

```fortran
program test
  error stop trim('foo')
end program test
```

**Pull request merged**
