### PR TITLE
Fix #513

### LINKED ISSUE #513: compiler error: outx_id: PROC_EXT_ID is NULL: symbol=nf_inq_libvers
```fortran
MODULE mo_netcdf_param
public
  character*80   nf_inq_libvers
  external       nf_inq_libvers
END MODULE mo_netcdf_param
```
```fortran
MODULE test

USE mo_netcdf_param

END MODULE test
```
Xmod file 
```xml
<OmniFortranModule version="1.0">
  <name>mo_netcdf_param</name>
  <depends>
  </depends>
  <typeTable>
    <FfunctionType type="F7ff9c349ed30" return_type="C7ff9c349eaf0" is_external="true"/>
    <FbasicType type="C7ff9c349ec10" ref="Fcharacter">
      <len>
        <FintConstant type="Fint">80</FintConstant>
      </len>
    </FbasicType>
    <FbasicType type="C7ff9c349eaf0" ref="C7ff9c349ec10"/>
    <FbasicType type="F7ff9c349ee50" is_public="true" ref="F7ff9c349ed30"/>
  </typeTable>
  <identifiers>
    <id type="F7ff9c349ee50" sclass="ffunc" original_name="nf_inq_libvers" declared_in="mo_netcdf_param">
      <name>nf_inq_libvers</name>
    </id>
  </identifiers>
  <declarations>
  </declarations>
  <interfaceDecls>
  </interfaceDecls>
  <aux_info>
  </aux_info>
</OmniFortranModule>
```

This code lead to the following error: 
```bash
"dummy.f90:test", line 5: compiler error: outx_id: PROC_EXT_ID is NULL: symbol=nf_inq_libvers
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by clementval**
Fix for issue #513

### CODE REVIEW

**Comment by h-murai** [comment]
@clementval In this case, isn't it needed to recursively follow the `TYPE_REF` link, like in `has_attr_in_types`?

**Comment by clementval** [comment]
@h-murai Probably but here, the information is stored in `TYPE_ENTRY` and it doesn't have the information about the `ref` type. Maybe we should save this info like the `parent_type_id` but `ref_type_id` to be able to go through recursively ... What do you think?

**Comment by clementval** [comment]
@shingo-s @h-murai What is your opinion on this? I can make the change today if you think it makes sense.

**Comment by h-murai** [comment]
@clementval I think you can do it if it's useful in other parts of F_Front.

**Comment by clementval** [comment]
@h-murai Ok, I'll do it then.

**Comment by clementval** [comment]
@h-murai I did the change

**Pull request merged**
