### PR TITLE
Fix for issue #168: incompatible dimension for the operation

### PR DESCRIPTION
**Pull request by clementval**
When the code is iterating over all potential function, no error should be thrown as the correct function is find after. 

@shingo-s @h-murai Don't know if this is the best way to do it but it works.

### CODE REVIEW

**Comment by shingo-s** [comment]
It seems to be not good, but it will work well. So it can be merged.

**Comment by h-murai** [comment]
@shingo-s What's the "not good" point? You mean "it isn't the best way but could resolve the problem as a quick fix, as @clementval said"?

**Comment by shingo-s** [comment]
@h-murai 

> @shingo-s What's the "not good" point? You mean "it isn't the best way but could resolve the problem as a quick fix, as @clementval said"?

Yes.
It is not good code because it is just a quick fix and ignore the error.

**Comment by clementval** [comment]
@h-murai @shingo-s I agree there is probably a better way. The thing is that `are_dimension_and_shape_conformant_by_type` is called two or three times with the wrong subroutine before finding the correct one. Therefore, even after finding the correct one, the code will abort because of the previous attempt with other subroutine in the interface. 
If you think there is a better way, I'll gladly spend time implementing it.

**Comment by clementval** [comment]
@h-murai @shingo-s Thanks for the merge. Anyway, I'll check it again with the problem related to #143. It seems to be a global things around generic function.

**Pull request merged**
