### PR TITLE
Accept function with return type and keyword as a name (issue #191)

### PR DESCRIPTION
**Pull request by clementval**
This PR fixes issue #191

### CODE REVIEW

**Comment by h-murai** [comment]
@clementval Sorry. Some conflicts occur for this PR while I delayed merging it and I couldn't resolve them. Could you re-create the pull request?

**Comment by clementval** [comment]
@h-murai No problem, I currently trying to re-apply the fix but the parser changed quite a lot so it will take me some time.

**Comment by clementval** [comment]
@h-murai I fixed the conflict

**Comment by clementval** [comment]
@h-murai Thanks for the merge!

**Pull request merged**
