### PR TITLE
IEEE intrinsic modules

### PR DESCRIPTION
**Pull request by clementval**
Modules signatures taken from gfortran. 

`HAVE_GFC_REAL_10` and `HAVE_GFC_REAL_16` should be defined at configuration time if we want to enable those kind of reals.

### CODE REVIEW

**Comment by clementval** [comment]
@h-murai Would this be merged at some point or should I close the PR?

**Comment by h-murai** [comment]
@clementval This is a little complicated problem and I couldn't make a decision for long time. I have a question. Are the files such as `ieee_arithmetic.f90` found in the install directory, or only in the source codes of the compilers?

**Comment by clementval** [comment]
@h-murai These are the files as in the source code. With some modifications.
If these need some update or to do them in a different way, just let me know.

**Comment by clementval** [comment]
Migrated to omni-compiler/xcodeml-tools#11

**Pull request closed without merging**
